### PR TITLE
Generic OAuth2 support and support for header propagation

### PR DESCRIPTION
**Pull request by jasmdk**
In order for us to reuse your terminology editor, we need to generalize the authentication so that it is not limited to Auth0, but to any oauth2 complient IDP.
Items changed:
- Downgraded docker image to node-10 to avoid various warnings
- Specifying a user to avoid running container as root (which is not recommended)
- Replacing auth0.js with angular-oauth2-oidc
- Fixing default security namespace when not using Auth0 - would be empty when creating the user which is invalid
- Aligning user claim names with OIDC instead of being Auth0 specific
- Include hpropagate and optionally propagate headers to the backend terminology server (authorization token and distributed tracing headers in our case)
- Upgrading a few recommended librarys (npm audit fix)

### CODE REVIEW

**Comment by seanmcilvenna** [comment]
This is really great! Would you please create this PR against the "development" branch, instead. We use the "development" branch for the latest changes, and then merge the development branch into the master branch when we're getting ready to release a new version.

**Comment by seanmcilvenna** [comment]
According to GitHub, there are still a few conflicting files...
* apps/client/src/app/shared/auth.service.ts
* package-lock.json
* package.json

**Comment by jasmdk** [comment]
Should be fixed now.
Unfortunately it seems like the direction the development branch is moving in does not match the scenario we intend to use trifolia-on-fhir for. We would like to use this as an editor for terminology-resources so that publishing a changed codesystem/valueset can be available immediately throughout our service architecture, but scoping it by a project does not allow us to find the existing value sets as they are not scoped by an implementation guide

**Comment by seanmcilvenna** [comment]
Ahhh. Interesting use-case! The functionality of the screen's themselves do not _require_ an implementation guide. It's really just the Angular URL routing that requires the implementation guide (with the exception of the Implementation Guide Edit screen, itself). I'd love to see a PR that makes "implementation guide context" an option, rather than being required like it is in the development branch.

**Comment by seanmcilvenna** [comment]
sorry for the delay. we've had one of our developers working on basically the same changes. but, they just started on them a little bit ago, so we've been comparing branches trying to determine what direction to take. stay tuned.

**Comment by seanmcilvenna** [comment]
This has been merged. We made a couple minor changes... made sure logging out redirected user to the auth provider's /logout operation. A couple other things I can't remember. The `development` branch will be merged with `master` when we next do a new version/release.

**Pull request merged**
